# Site settings
baseurl = "https://carloscordon.github.io/"
languageCode = "en-us"
title = "Ebanistería Cordón"
theme = "artists"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Ebanistería Cordón"
	description = ""

	# Since this template is static, the contact form uses www.formspree.io as a
	# proxy. The form makes a POST request to their servers to send the actual
	# email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
	email = "raquelmarinezquerro@yahoo.es"


	# Header an navigation
	#
	# To change the header background the 'hero-bg-jpg' at 'static/img'.
	# Do the same with the logo ('logo.svg').
	# But keep the original filename!
	[params.header]
		title = "Ebanistería Cordón"
		shortBio = "Ebanistería sin compromisos"


	# About section
	#
	# Replace the 'avatar.jpg' under 'static/img' with your own image.
	[params.about]
		title = "QUIENES SOMOS"
		bio = "Somos una empresa dedicada a la carpintería y ebanistería con mas de 18 años de experiencia profesional. Nos dedicamos a la fabricación e instalación de muebles a medida, puertas,ventanas, cocinas, suelos, escaleras, armarios empotrados...\r\nAsesorando en la distribución y cuidando mucho los acabados para la mayor satisfacción del cliente. Colaboramos con arquitectos, interioristas, escenógrafos, diseñadores y empresas de reformas."

	# Contact secion
	[params.contact]
		title = "Contacto"

		# The following social network icons are available:
		# 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin'
		# 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
		#[[params.contact.social]]
		#	icon = "twitter"
		#		link = "//twitter.com/devtipsshow"

		#[[params.contact.social]]
		#	icon = "dribbble"
		#	link = "//dribbble.com/travisneilson"

		#[[params.contact.social]]
		#	icon = "behance"
		#	link = "//www.behance.net/travisneilson"

		#[[params.contact.social]]
		#	icon = "youtube"
		#	link = "//www.youtube.com/DevTipsForDesigners"

		[[params.contact.social]]
			icon = "linkedin"
			link = "//www.linkedin.com/in/carlos-cordón-ezquerro-50804652"

		[[params.contact.social]]
			icon = "facebook"
			link = "//www.linkedin.com/in/carlos-cordón-ezquerro-50804652"


	[params.form]
		title = "Pide presupuesto sin compromiso"
		# Form fields
		name = "Nombre"
		email = "Correo electrónico"
		message = "¿Qué necesitas?"
		buttonText = "Enviar"


	[params.footer]
		copyright = " "
